sonar.projectName=Stone.js - Azure Functions HTTP Adapter
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-azure-functions-http-adapter
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Azure Functions v4 HTTP adapter for Stone.js. Run your app on Azure Functions HTTP triggers using the Continuum Architecture.
