sonar.projectName=Stone.js - Browser Adapter
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-browser-adapter
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Browser adapter for Stone.js. Enables SPA runtime support, unified event handling, and cookie management in the browser, part of the Continuum Architecture.

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=browser-adapter
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8