sonar.projectName=Stone.js - Alibaba FC HTTP Adapter
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-alibaba-fc-http-adapter
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Alibaba Cloud Function Compute HTTP adapter for Stone.js. Run your app on FC HTTP triggers using the Continuum Architecture.
