sonar.projectName=Stone.js - Cache
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-cache
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Agnostic cache for Stone.js (memory + Redis) with tags, remember and cache decorators.
