sonar.projectName=Stone.js - React Native Adapter
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-react-native-adapter
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=React Native adapter for Stone.js. Turns deep links, in-app navigation and app-state changes into Stone.js events, part of the Continuum Architecture.
