import { join } from 'node:path'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { CliError } from '../errors/CliError'
import { ADAPTER_PLATFORMS, KNOWN_PLATFORMS, packageProviding, packagesToExclude } from './platforms'

/**
 * The adapter packages a project depends on.
 *
 * @param dependencies - The project's dependency names.
 * @returns The adapter packages among them.
 */
export function installedAdapters (dependencies: string[]): string[] {
  return dependencies.filter((name) => ADAPTER_PLATFORMS[name] !== undefined)
}

/**
 * Check that a requested platform can actually be built, and say what to do when it cannot.
 *
 * Failing here is the point. A targeted build that silently produced an artefact for a platform the
 * application never enabled would deploy, start, and find no adapter to answer with, which is the
 * worst possible moment to learn about it.
 *
 * @param platform - The requested platform.
 * @param dependencies - The project's dependency names.
 * @throws {CliError} When the platform is unknown, or its adapter is not a dependency.
 */
export function assertPlatformIsBuildable (platform: string, dependencies: string[]): void {
  if (!KNOWN_PLATFORMS.includes(platform)) {
    throw new CliError(
      `Unknown platform '${platform}'.\nAvailable: ${KNOWN_PLATFORMS.join(', ')}.`
    )
  }

  const pkg = packageProviding(platform)

  if (pkg !== undefined && !dependencies.includes(pkg)) {
    throw new CliError(
      `Cannot build for '${platform}': this project does not depend on ${pkg}.\n` +
      'Install it and enable it on the application, then build again:\n' +
      `  npm i ${pkg}\n` +
      '  // then add its decorator (or its blueprint) to your application manifest'
    )
  }
}

/**
 * Source for a stub standing in for an excluded adapter package.
 *
 * The names are taken from what the application actually imports, so the stub satisfies exactly the
 * bindings the bundler asks for and nothing more. Every one is inert: a decorator that decorates
 * nothing, a blueprint that contributes nothing. That is safe precisely because the platform was not
 * selected, so this adapter's blueprint entry is never chosen and its adapter never instantiated.
 *
 * @param names - The named imports to satisfy.
 * @returns The stub module source.
 */
export function stubSource (names: string[]): string {
  const decls = names.map((name) => (
    // A single inert shape serves all of them: called as a decorator it returns a no-op decorator,
    // read as a blueprint it is an empty object, used as a class it constructs to nothing.
    `export const ${name} = /* @__PURE__ */ Object.assign(function () { return function () {} }, { stone: {} })`
  ))

  return [
    '// Generated by @stone-js/cli --platform: this adapter is not the selected platform.',
    ...decls,
    'export default {}'
  ].join('\n')
}

/**
 * The names a module source declares, in either shape a bundler emits.
 *
 * Rollup ends a bundle with `export { a, b as c }`; a hand-written or differently-bundled module uses
 * `export const a`. Both are read, so the stub is complete whichever produced the file.
 *
 * @param source - The module source.
 * @returns The exported names, `default` excluded.
 */
export function parseExportNames (source: string): string[] {
  const names = new Set<string>()

  for (const match of source.matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const part of match[1].split(',')) {
      const name = part.trim().split(/\s+as\s+/).pop()?.trim()
      if (name !== undefined && /^[A-Za-z_$][\w$]*$/.test(name) && name !== 'default') { names.add(name) }
    }
  }

  for (const match of source.matchAll(/export\s+(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/g)) {
    names.add(match[1])
  }

  return [...names]
}

/**
 * The names a built package exports, read from its own bundle.
 *
 * Deterministic and complete: the stub declares exactly what the real module declares, so whatever
 * the application imports resolves. Guessing from the import sites would miss a re-export.
 *
 * @param pkg - The package name.
 * @param resolveFrom - Where to resolve the package from.
 * @returns The exported names, or an empty list when the bundle cannot be read.
 */
export function exportedNames (pkg: string, resolveFrom: string = process.cwd()): string[] {
  try {
    const entry = createRequire(join(resolveFrom, 'noop.js')).resolve(pkg)
    return parseExportNames(readFileSync(entry, 'utf-8'))
  } catch {
    return []
  }
}

/**
 * A Rollup plugin that replaces the adapter packages a targeted build must not ship.
 *
 * Each excluded package resolves to a virtual module whose stub declares the same names the real one
 * does, every one inert. That is safe precisely because the platform was not selected: this adapter's
 * blueprint entry is never chosen and its adapter never instantiated, so nothing ever calls into it.
 *
 * @param platform - The selected platform.
 * @param dependencies - The project's dependency names.
 * @param resolveFrom - Where to resolve the excluded packages from.
 * @returns A Rollup plugin, or `undefined` when nothing needs excluding.
 */
export function platformStubsPlugin (platform: string, dependencies: string[], resolveFrom?: string): any {
  const excluded = packagesToExclude(platform, installedAdapters(dependencies))

  if (excluded.length === 0) { return undefined }

  const prefix = '\0stone-platform-stub:'

  return {
    name: 'stone-platform-stubs',

    resolveId (source: string) {
      const pkg = excluded.find((name) => source === name || source.startsWith(`${name}/`))
      return pkg === undefined ? null : `${prefix}${pkg}`
    },

    load (id: string) {
      if (!id.startsWith(prefix)) { return null }
      return stubSource(exportedNames(id.slice(prefix.length), resolveFrom))
    }
  }
}

/**
 * The excluded packages, for reporting.
 *
 * @param platform - The selected platform.
 * @param dependencies - The project's dependency names.
 * @returns The excluded package names.
 */
export function excludedFor (platform: string, dependencies: string[]): string[] {
  return packagesToExclude(platform, installedAdapters(dependencies))
}
