import { NODE_CONSOLE_PLATFORM } from './constants'
import { McpCommand, mcpCommandOptions } from './commands/McpCommand'
import { BlueprintContext, ClassType, IBlueprint, NextMiddleware } from '@stone-js/core'
import type { StoneCliPlugin, StonePluginBlueprintMiddleware, StonePluginContext } from '@stone-js/cli'

/**
 * Register the `mcp` command on the CLI.
 *
 * Contributed by the plugin rather than by the application, which is the whole point: introspection is
 * a development concern, and an application should not have to declare a development tool to get one.
 * The CLI runs plugin blueprint middleware in its own pipeline, and the CLI is itself a Stone.js app on
 * the console platform, so the command lands exactly where every other command does.
 *
 * @param context - The blueprint context.
 * @param next - The next middleware.
 * @returns The blueprint.
 */
export const SetMcpCommandsMiddleware = async (
  context: BlueprintContext<IBlueprint, ClassType>,
  next: NextMiddleware<BlueprintContext<IBlueprint, ClassType>, IBlueprint>
): Promise<IBlueprint> => {
  if (context.blueprint.get<string>('stone.adapter.platform') === NODE_CONSOLE_PLATFORM) {
    context.blueprint.add('stone.adapter.commands', [{ options: mcpCommandOptions, isClass: true, module: McpCommand }])
  }

  return await next(context)
}

/** The blueprint middleware this plugin contributes. */
export const mcpDevPluginMiddleware: StonePluginBlueprintMiddleware[] = [
  { module: SetMcpCommandsMiddleware, priority: 5 }
]

/** Where the plugin writes the module it injects, relative to the build's `.stone/tmp` directory. */
export const GENERATED_MODULE: string = 'plugins/mcp-dev-context.mjs'

/** The commands that mean "a developer is working right now", and nothing else. */
export const DEV_COMMANDS: string[] = ['dev', 'serve', 'preview']

/**
 * The module injected into a development build.
 *
 * It contributes one lifecycle hook, and imports the publishing helper from the package rather than
 * restating it, so the file format and the redaction rules keep living in one place.
 *
 * @returns The generated module's source.
 */
export function generatedModule (): string {
  return [
    '// Generated by the @stone-js/mcp-dev CLI plugin, for development builds only.',
    "import { publishAppContext } from '@stone-js/mcp-dev'",
    '',
    'export const mcpDevContextBlueprint = {',
    '  stone: {',
    '    lifecycleHooks: {',
    '      onStart: [({ blueprint }) => { try { publishAppContext(blueprint) } catch {} }]',
    '    }',
    '  }',
    '}',
    ''
  ].join('\n')
}

/**
 * The MCP dev CLI plugin.
 *
 * Introspection is a development concern, so it belongs to the build rather than to the application.
 * Declaring it in the app would put a development tool in the application's own module graph — and
 * make a production build depend on a package the application does not need — for a feature nobody
 * uses in production. The build already knows when a developer is working, which is exactly when this
 * is wanted, so the build is where it is decided.
 *
 * What it does, in one sentence: on a development build it injects a hook that makes the running
 * application publish its resolved configuration, so `stone mcp` describes **that** application
 * instead of the console boot it can reach by itself.
 *
 * Nothing is injected into a production build, and nothing has to be imported by the app.
 *
 * @returns The plugin.
 */
export function mcpDevCliPlugin (): StoneCliPlugin {
  return {
    name: '@stone-js/mcp-dev',
    description: 'Adds `stone mcp`, and lets it introspect the app you are actually running',

    blueprintMiddleware: mcpDevPluginMiddleware,

    onPrepare: async (context: StonePluginContext): Promise<void> => {
      // Only while developing: a production artifact must carry none of this.
      if (!DEV_COMMANDS.includes(context.command)) { return }

      // The build decides presence, so the build is where turning it off belongs: an application that
      // opts out gets nothing injected, rather than shipping code that decides not to run.
      if (!context.blueprint.get<boolean>('stone.builder.mcpDev.publishContext', true)) { return }

      context.writeFile(GENERATED_MODULE, generatedModule())
      context.addModule(`./${GENERATED_MODULE}`)
    }
  }
}

/**
 * A ready-to-use plugin instance, used by first-party `package.json` auto-discovery.
 */
const plugin: StoneCliPlugin = mcpDevCliPlugin()
export default plugin
