sonar.projectName=Stone.js - Queue
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-queue
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Agnostic job queue for Stone.js (memory + Redis) with delay, retries, a worker and decorators.
