sonar.projectName=Stone.js - Tencent SCF HTTP Adapter
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-tencent-scf-http-adapter
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Tencent Cloud SCF HTTP adapter for Stone.js. Run your app on SCF HTTP triggers using the Continuum Architecture.
