import { readFileSync, writeFileSync } from 'node:fs'

/**
 * Keep the site header version aligned with the published Stone.js version, automatically.
 *
 * Reads the version of `@stone-js/core` the site is built against (a lockstep `workspace:*`
 * dependency, so it equals the version being released), and writes it into `app/version.ts`.
 * Run before every dev/build so the header never drifts from the latest published release, the
 * same way the starter commands always pull `@stone-js@latest`.
 */
const version = JSON.parse(readFileSync('node_modules/@stone-js/core/package.json', 'utf8')).version

const content = `// Generated by scripts/sync-version.mjs. Do not edit by hand.
// The published @stone-js/* version, kept in sync with @stone-js/core at build time.
export const APP_VERSION = '${version}'
`

writeFileSync('app/version.ts', content)
console.log(`sync-version: app.version = ${version}`)
