sonar.projectName=Stone.js - GCP Cloud Functions Adapter
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-gcp-cloud-functions-adapter
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=General-purpose GCP Cloud Functions adapter for Stone.js. Run any app on event-driven Cloud Functions (CloudEvents) using the Continuum Architecture.
