/**
 * Platform polyfills come first, before anything from Stone.js loads.
 *
 * - React Native's built-in `URL` is a stub (no `pathname`, no `searchParams`), and the router
 *   reads `pathname` on every event, so the polyfill is required rather than nice to have.
 * - `TextEncoder` is installed only when the engine does not provide it (older Hermes).
 */
import 'react-native-url-polyfill/auto'

if (typeof globalThis.TextEncoder === 'undefined') {
  require('fast-text-encoding')
}

import { stoneApp } from '@stone-js/core'
import { registerRootComponent } from 'expo'
import App from './App'

/**
 * Every module under `app/`, collected at build time.
 *
 * Generated by `withStone` in `metro.config.js`, because collecting modules is a bundler question
 * and Metro has no `import.meta.glob`. Never edit it, never commit it.
 */
import { modules } from './.stone/modules'

// Boot the framework, then hand the root component to Expo. `registerRootComponent` works the same
// in Expo Go and in a native build.
void stoneApp({ modules }).run()

registerRootComponent(App)
