sonar.projectName=Stone.js - Browser Core
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-browser-core
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Stone.js Browser core provides essential utilities for browser-based applications, including event handling, response management, and cookie operations.

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=browser-core
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8