sonar.projectName=Stone.js - Use React Core
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-use-react-core
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts, **/*.spec.tsx, **/*.test.tsx
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=The platform-independent half of Stone.js's React integration, shared by the web and native renderers.
