sonar.projectName=Stone.js - Cloud File
sonar.organization=stone-foundation
sonar.projectKey=stone-foundation_stone-js-cloud-file
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.projectDescription=Cloud storage drivers for the Stone.js agnostic filesystem contract (S3 + S3-compatible) with signed URLs.
